// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetTasksDeprecatedReader is a Reader for the GetTasksDeprecated structure.
type GetTasksDeprecatedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTasksDeprecatedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTasksDeprecatedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTasksDeprecatedOK creates a GetTasksDeprecatedOK with default headers values
func NewGetTasksDeprecatedOK() *GetTasksDeprecatedOK {
	return &GetTasksDeprecatedOK{}
}

/*
GetTasksDeprecatedOK describes a response with status code 200, with default header values.

successful operation
*/
type GetTasksDeprecatedOK struct {
	Payload []string
}

// IsSuccess returns true when this get tasks deprecated o k response has a 2xx status code
func (o *GetTasksDeprecatedOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get tasks deprecated o k response has a 3xx status code
func (o *GetTasksDeprecatedOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tasks deprecated o k response has a 4xx status code
func (o *GetTasksDeprecatedOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get tasks deprecated o k response has a 5xx status code
func (o *GetTasksDeprecatedOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get tasks deprecated o k response a status code equal to that given
func (o *GetTasksDeprecatedOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get tasks deprecated o k response
func (o *GetTasksDeprecatedOK) Code() int {
	return 200
}

func (o *GetTasksDeprecatedOK) Error() string {
	return fmt.Sprintf("[GET /tasks/tasks/{taskType}][%d] getTasksDeprecatedOK  %+v", 200, o.Payload)
}

func (o *GetTasksDeprecatedOK) String() string {
	return fmt.Sprintf("[GET /tasks/tasks/{taskType}][%d] getTasksDeprecatedOK  %+v", 200, o.Payload)
}

func (o *GetTasksDeprecatedOK) GetPayload() []string {
	return o.Payload
}

func (o *GetTasksDeprecatedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
