// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetTaskStateReader is a Reader for the GetTaskState structure.
type GetTaskStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTaskStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTaskStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTaskStateOK creates a GetTaskStateOK with default headers values
func NewGetTaskStateOK() *GetTaskStateOK {
	return &GetTaskStateOK{}
}

/*
GetTaskStateOK describes a response with status code 200, with default header values.

successful operation
*/
type GetTaskStateOK struct {
	Payload string
}

// IsSuccess returns true when this get task state o k response has a 2xx status code
func (o *GetTaskStateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get task state o k response has a 3xx status code
func (o *GetTaskStateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get task state o k response has a 4xx status code
func (o *GetTaskStateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get task state o k response has a 5xx status code
func (o *GetTaskStateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get task state o k response a status code equal to that given
func (o *GetTaskStateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get task state o k response
func (o *GetTaskStateOK) Code() int {
	return 200
}

func (o *GetTaskStateOK) Error() string {
	return fmt.Sprintf("[GET /tasks/task/{taskName}/state][%d] getTaskStateOK  %+v", 200, o.Payload)
}

func (o *GetTaskStateOK) String() string {
	return fmt.Sprintf("[GET /tasks/task/{taskName}/state][%d] getTaskStateOK  %+v", 200, o.Payload)
}

func (o *GetTaskStateOK) GetPayload() string {
	return o.Payload
}

func (o *GetTaskStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
