// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStopTasksParams creates a new StopTasksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopTasksParams() *StopTasksParams {
	return &StopTasksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopTasksParamsWithTimeout creates a new StopTasksParams object
// with the ability to set a timeout on a request.
func NewStopTasksParamsWithTimeout(timeout time.Duration) *StopTasksParams {
	return &StopTasksParams{
		timeout: timeout,
	}
}

// NewStopTasksParamsWithContext creates a new StopTasksParams object
// with the ability to set a context for a request.
func NewStopTasksParamsWithContext(ctx context.Context) *StopTasksParams {
	return &StopTasksParams{
		Context: ctx,
	}
}

// NewStopTasksParamsWithHTTPClient creates a new StopTasksParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopTasksParamsWithHTTPClient(client *http.Client) *StopTasksParams {
	return &StopTasksParams{
		HTTPClient: client,
	}
}

/*
StopTasksParams contains all the parameters to send to the API endpoint

	for the stop tasks operation.

	Typically these are written to a http.Request.
*/
type StopTasksParams struct {

	/* TaskType.

	   Task type
	*/
	TaskType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopTasksParams) WithDefaults() *StopTasksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopTasksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop tasks params
func (o *StopTasksParams) WithTimeout(timeout time.Duration) *StopTasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop tasks params
func (o *StopTasksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop tasks params
func (o *StopTasksParams) WithContext(ctx context.Context) *StopTasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop tasks params
func (o *StopTasksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop tasks params
func (o *StopTasksParams) WithHTTPClient(client *http.Client) *StopTasksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop tasks params
func (o *StopTasksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTaskType adds the taskType to the stop tasks params
func (o *StopTasksParams) WithTaskType(taskType string) *StopTasksParams {
	o.SetTaskType(taskType)
	return o
}

// SetTaskType adds the taskType to the stop tasks params
func (o *StopTasksParams) SetTaskType(taskType string) {
	o.TaskType = taskType
}

// WriteToRequest writes these params to a swagger request
func (o *StopTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param taskType
	if err := r.SetPathParam("taskType", o.TaskType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
