// Code generated by go-swagger; DO NOT EDIT.

package atomic_ingestion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new atomic ingestion API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for atomic ingestion API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	EndDataIngestRequest(params *EndDataIngestRequestParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error

	StartDataIngestRequest(params *StartDataIngestRequestParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error

	SetTransport(transport runtime.ClientTransport)
}

/*
EndDataIngestRequest marks the end of data ingestion to upload multiple segments
*/
func (a *Client) EndDataIngestRequest(params *EndDataIngestRequestParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewEndDataIngestRequestParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "endDataIngestRequest",
		Method:             "POST",
		PathPattern:        "/segments/{tableName}/endDataIngestRequest",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &EndDataIngestRequestReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	_, err := a.transport.Submit(op)
	if err != nil {
		return err
	}
	return nil
}

/*
StartDataIngestRequest marks the start of data ingestion to upload multiple segments
*/
func (a *Client) StartDataIngestRequest(params *StartDataIngestRequestParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStartDataIngestRequestParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "startDataIngestRequest",
		Method:             "POST",
		PathPattern:        "/segments/{tableName}/startDataIngestRequest",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StartDataIngestRequestReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	_, err := a.transport.Submit(op)
	if err != nil {
		return err
	}
	return nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
