// Code generated by go-swagger; DO NOT EDIT.

package atomic_ingestion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewEndDataIngestRequestParams creates a new EndDataIngestRequestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEndDataIngestRequestParams() *EndDataIngestRequestParams {
	return &EndDataIngestRequestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEndDataIngestRequestParamsWithTimeout creates a new EndDataIngestRequestParams object
// with the ability to set a timeout on a request.
func NewEndDataIngestRequestParamsWithTimeout(timeout time.Duration) *EndDataIngestRequestParams {
	return &EndDataIngestRequestParams{
		timeout: timeout,
	}
}

// NewEndDataIngestRequestParamsWithContext creates a new EndDataIngestRequestParams object
// with the ability to set a context for a request.
func NewEndDataIngestRequestParamsWithContext(ctx context.Context) *EndDataIngestRequestParams {
	return &EndDataIngestRequestParams{
		Context: ctx,
	}
}

// NewEndDataIngestRequestParamsWithHTTPClient creates a new EndDataIngestRequestParams object
// with the ability to set a custom HTTPClient for a request.
func NewEndDataIngestRequestParamsWithHTTPClient(client *http.Client) *EndDataIngestRequestParams {
	return &EndDataIngestRequestParams{
		HTTPClient: client,
	}
}

/*
EndDataIngestRequestParams contains all the parameters to send to the API endpoint

	for the end data ingest request operation.

	Typically these are written to a http.Request.
*/
type EndDataIngestRequestParams struct {

	/* CheckpointEntryKey.

	   Key of checkpoint entry
	*/
	CheckpointEntryKey string

	/* TableName.

	   Name of the table
	*/
	TableName string

	/* TableType.

	   OFFLINE|REALTIME
	*/
	TableType string

	/* TaskType.

	   Task type
	*/
	TaskType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the end data ingest request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EndDataIngestRequestParams) WithDefaults() *EndDataIngestRequestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the end data ingest request params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EndDataIngestRequestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the end data ingest request params
func (o *EndDataIngestRequestParams) WithTimeout(timeout time.Duration) *EndDataIngestRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the end data ingest request params
func (o *EndDataIngestRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the end data ingest request params
func (o *EndDataIngestRequestParams) WithContext(ctx context.Context) *EndDataIngestRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the end data ingest request params
func (o *EndDataIngestRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the end data ingest request params
func (o *EndDataIngestRequestParams) WithHTTPClient(client *http.Client) *EndDataIngestRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the end data ingest request params
func (o *EndDataIngestRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCheckpointEntryKey adds the checkpointEntryKey to the end data ingest request params
func (o *EndDataIngestRequestParams) WithCheckpointEntryKey(checkpointEntryKey string) *EndDataIngestRequestParams {
	o.SetCheckpointEntryKey(checkpointEntryKey)
	return o
}

// SetCheckpointEntryKey adds the checkpointEntryKey to the end data ingest request params
func (o *EndDataIngestRequestParams) SetCheckpointEntryKey(checkpointEntryKey string) {
	o.CheckpointEntryKey = checkpointEntryKey
}

// WithTableName adds the tableName to the end data ingest request params
func (o *EndDataIngestRequestParams) WithTableName(tableName string) *EndDataIngestRequestParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the end data ingest request params
func (o *EndDataIngestRequestParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WithTableType adds the tableType to the end data ingest request params
func (o *EndDataIngestRequestParams) WithTableType(tableType string) *EndDataIngestRequestParams {
	o.SetTableType(tableType)
	return o
}

// SetTableType adds the tableType to the end data ingest request params
func (o *EndDataIngestRequestParams) SetTableType(tableType string) {
	o.TableType = tableType
}

// WithTaskType adds the taskType to the end data ingest request params
func (o *EndDataIngestRequestParams) WithTaskType(taskType string) *EndDataIngestRequestParams {
	o.SetTaskType(taskType)
	return o
}

// SetTaskType adds the taskType to the end data ingest request params
func (o *EndDataIngestRequestParams) SetTaskType(taskType string) {
	o.TaskType = taskType
}

// WriteToRequest writes these params to a swagger request
func (o *EndDataIngestRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param checkpointEntryKey
	qrCheckpointEntryKey := o.CheckpointEntryKey
	qCheckpointEntryKey := qrCheckpointEntryKey
	if qCheckpointEntryKey != "" {

		if err := r.SetQueryParam("checkpointEntryKey", qCheckpointEntryKey); err != nil {
			return err
		}
	}

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	// query param tableType
	qrTableType := o.TableType
	qTableType := qrTableType
	if qTableType != "" {

		if err := r.SetQueryParam("tableType", qTableType); err != nil {
			return err
		}
	}

	// query param taskType
	qrTaskType := o.TaskType
	qTaskType := qrTaskType
	if qTaskType != "" {

		if err := r.SetQueryParam("taskType", qTaskType); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
