// Code generated by go-swagger; DO NOT EDIT.

package write_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetWriteConfigReader is a Reader for the GetWriteConfig structure.
type GetWriteConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWriteConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewGetWriteConfigDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewGetWriteConfigDefault creates a GetWriteConfigDefault with default headers values
func NewGetWriteConfigDefault(code int) *GetWriteConfigDefault {
	return &GetWriteConfigDefault{
		_statusCode: code,
	}
}

/*
GetWriteConfigDefault describes a response with status code -1, with default header values.

successful operation
*/
type GetWriteConfigDefault struct {
	_statusCode int
}

// IsSuccess returns true when this get write config default response has a 2xx status code
func (o *GetWriteConfigDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get write config default response has a 3xx status code
func (o *GetWriteConfigDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get write config default response has a 4xx status code
func (o *GetWriteConfigDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get write config default response has a 5xx status code
func (o *GetWriteConfigDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get write config default response a status code equal to that given
func (o *GetWriteConfigDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get write config default response
func (o *GetWriteConfigDefault) Code() int {
	return o._statusCode
}

func (o *GetWriteConfigDefault) Error() string {
	return fmt.Sprintf("[GET /v1/write/config/{table}][%d] getWriteConfig default ", o._statusCode)
}

func (o *GetWriteConfigDefault) String() string {
	return fmt.Sprintf("[GET /v1/write/config/{table}][%d] getWriteConfig default ", o._statusCode)
}

func (o *GetWriteConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
