// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddTableParams creates a new AddTableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddTableParams() *AddTableParams {
	return &AddTableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddTableParamsWithTimeout creates a new AddTableParams object
// with the ability to set a timeout on a request.
func NewAddTableParamsWithTimeout(timeout time.Duration) *AddTableParams {
	return &AddTableParams{
		timeout: timeout,
	}
}

// NewAddTableParamsWithContext creates a new AddTableParams object
// with the ability to set a context for a request.
func NewAddTableParamsWithContext(ctx context.Context) *AddTableParams {
	return &AddTableParams{
		Context: ctx,
	}
}

// NewAddTableParamsWithHTTPClient creates a new AddTableParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddTableParamsWithHTTPClient(client *http.Client) *AddTableParams {
	return &AddTableParams{
		HTTPClient: client,
	}
}

/*
AddTableParams contains all the parameters to send to the API endpoint

	for the add table operation.

	Typically these are written to a http.Request.
*/
type AddTableParams struct {

	// Body.
	Body string

	/* ValidationTypesToSkip.

	   comma separated list of validation type(s) to skip. supported types: (ALL|TASK|UPSERT)
	*/
	ValidationTypesToSkip *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add table params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddTableParams) WithDefaults() *AddTableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add table params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddTableParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add table params
func (o *AddTableParams) WithTimeout(timeout time.Duration) *AddTableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add table params
func (o *AddTableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add table params
func (o *AddTableParams) WithContext(ctx context.Context) *AddTableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add table params
func (o *AddTableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add table params
func (o *AddTableParams) WithHTTPClient(client *http.Client) *AddTableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add table params
func (o *AddTableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add table params
func (o *AddTableParams) WithBody(body string) *AddTableParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add table params
func (o *AddTableParams) SetBody(body string) {
	o.Body = body
}

// WithValidationTypesToSkip adds the validationTypesToSkip to the add table params
func (o *AddTableParams) WithValidationTypesToSkip(validationTypesToSkip *string) *AddTableParams {
	o.SetValidationTypesToSkip(validationTypesToSkip)
	return o
}

// SetValidationTypesToSkip adds the validationTypesToSkip to the add table params
func (o *AddTableParams) SetValidationTypesToSkip(validationTypesToSkip *string) {
	o.ValidationTypesToSkip = validationTypesToSkip
}

// WriteToRequest writes these params to a swagger request
func (o *AddTableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.ValidationTypesToSkip != nil {

		// query param validationTypesToSkip
		var qrValidationTypesToSkip string

		if o.ValidationTypesToSkip != nil {
			qrValidationTypesToSkip = *o.ValidationTypesToSkip
		}
		qValidationTypesToSkip := qrValidationTypesToSkip
		if qValidationTypesToSkip != "" {

			if err := r.SetQueryParam("validationTypesToSkip", qValidationTypesToSkip); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
