// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddConfigParams creates a new AddConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddConfigParams() *AddConfigParams {
	return &AddConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddConfigParamsWithTimeout creates a new AddConfigParams object
// with the ability to set a timeout on a request.
func NewAddConfigParamsWithTimeout(timeout time.Duration) *AddConfigParams {
	return &AddConfigParams{
		timeout: timeout,
	}
}

// NewAddConfigParamsWithContext creates a new AddConfigParams object
// with the ability to set a context for a request.
func NewAddConfigParamsWithContext(ctx context.Context) *AddConfigParams {
	return &AddConfigParams{
		Context: ctx,
	}
}

// NewAddConfigParamsWithHTTPClient creates a new AddConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddConfigParamsWithHTTPClient(client *http.Client) *AddConfigParams {
	return &AddConfigParams{
		HTTPClient: client,
	}
}

/*
AddConfigParams contains all the parameters to send to the API endpoint

	for the add config operation.

	Typically these are written to a http.Request.
*/
type AddConfigParams struct {

	// Body.
	Body string

	/* ValidationTypesToSkip.

	   comma separated list of validation type(s) to skip. supported types: (ALL|TASK|UPSERT)
	*/
	ValidationTypesToSkip *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddConfigParams) WithDefaults() *AddConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add config params
func (o *AddConfigParams) WithTimeout(timeout time.Duration) *AddConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add config params
func (o *AddConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add config params
func (o *AddConfigParams) WithContext(ctx context.Context) *AddConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add config params
func (o *AddConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add config params
func (o *AddConfigParams) WithHTTPClient(client *http.Client) *AddConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add config params
func (o *AddConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add config params
func (o *AddConfigParams) WithBody(body string) *AddConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add config params
func (o *AddConfigParams) SetBody(body string) {
	o.Body = body
}

// WithValidationTypesToSkip adds the validationTypesToSkip to the add config params
func (o *AddConfigParams) WithValidationTypesToSkip(validationTypesToSkip *string) *AddConfigParams {
	o.SetValidationTypesToSkip(validationTypesToSkip)
	return o
}

// SetValidationTypesToSkip adds the validationTypesToSkip to the add config params
func (o *AddConfigParams) SetValidationTypesToSkip(validationTypesToSkip *string) {
	o.ValidationTypesToSkip = validationTypesToSkip
}

// WriteToRequest writes these params to a swagger request
func (o *AddConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.ValidationTypesToSkip != nil {

		// query param validationTypesToSkip
		var qrValidationTypesToSkip string

		if o.ValidationTypesToSkip != nil {
			qrValidationTypesToSkip = *o.ValidationTypesToSkip
		}
		qValidationTypesToSkip := qrValidationTypesToSkip
		if qValidationTypesToSkip != "" {

			if err := r.SetQueryParam("validationTypesToSkip", qValidationTypesToSkip); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
