// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"startree.ai/cli/models"
)

// AddConfigReader is a Reader for the AddConfig structure.
type AddConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddConfigOK creates a AddConfigOK with default headers values
func NewAddConfigOK() *AddConfigOK {
	return &AddConfigOK{}
}

/*
AddConfigOK describes a response with status code 200, with default header values.

successful operation
*/
type AddConfigOK struct {
	Payload *models.ConfigSuccessResponse
}

// IsSuccess returns true when this add config o k response has a 2xx status code
func (o *AddConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add config o k response has a 3xx status code
func (o *AddConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add config o k response has a 4xx status code
func (o *AddConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add config o k response has a 5xx status code
func (o *AddConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add config o k response a status code equal to that given
func (o *AddConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the add config o k response
func (o *AddConfigOK) Code() int {
	return 200
}

func (o *AddConfigOK) Error() string {
	return fmt.Sprintf("[POST /tableConfigs][%d] addConfigOK  %+v", 200, o.Payload)
}

func (o *AddConfigOK) String() string {
	return fmt.Sprintf("[POST /tableConfigs][%d] addConfigOK  %+v", 200, o.Payload)
}

func (o *AddConfigOK) GetPayload() *models.ConfigSuccessResponse {
	return o.Payload
}

func (o *AddConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigSuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
