// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetControllerJobsParams creates a new GetControllerJobsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetControllerJobsParams() *GetControllerJobsParams {
	return &GetControllerJobsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetControllerJobsParamsWithTimeout creates a new GetControllerJobsParams object
// with the ability to set a timeout on a request.
func NewGetControllerJobsParamsWithTimeout(timeout time.Duration) *GetControllerJobsParams {
	return &GetControllerJobsParams{
		timeout: timeout,
	}
}

// NewGetControllerJobsParamsWithContext creates a new GetControllerJobsParams object
// with the ability to set a context for a request.
func NewGetControllerJobsParamsWithContext(ctx context.Context) *GetControllerJobsParams {
	return &GetControllerJobsParams{
		Context: ctx,
	}
}

// NewGetControllerJobsParamsWithHTTPClient creates a new GetControllerJobsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetControllerJobsParamsWithHTTPClient(client *http.Client) *GetControllerJobsParams {
	return &GetControllerJobsParams{
		HTTPClient: client,
	}
}

/*
GetControllerJobsParams contains all the parameters to send to the API endpoint

	for the get controller jobs operation.

	Typically these are written to a http.Request.
*/
type GetControllerJobsParams struct {

	/* JobTypes.

	   Comma separated list of job types
	*/
	JobTypes *string

	/* TableName.

	   Name of the table
	*/
	TableName string

	/* Type.

	   OFFLINE|REALTIME
	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get controller jobs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetControllerJobsParams) WithDefaults() *GetControllerJobsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get controller jobs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetControllerJobsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get controller jobs params
func (o *GetControllerJobsParams) WithTimeout(timeout time.Duration) *GetControllerJobsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get controller jobs params
func (o *GetControllerJobsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get controller jobs params
func (o *GetControllerJobsParams) WithContext(ctx context.Context) *GetControllerJobsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get controller jobs params
func (o *GetControllerJobsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get controller jobs params
func (o *GetControllerJobsParams) WithHTTPClient(client *http.Client) *GetControllerJobsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get controller jobs params
func (o *GetControllerJobsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJobTypes adds the jobTypes to the get controller jobs params
func (o *GetControllerJobsParams) WithJobTypes(jobTypes *string) *GetControllerJobsParams {
	o.SetJobTypes(jobTypes)
	return o
}

// SetJobTypes adds the jobTypes to the get controller jobs params
func (o *GetControllerJobsParams) SetJobTypes(jobTypes *string) {
	o.JobTypes = jobTypes
}

// WithTableName adds the tableName to the get controller jobs params
func (o *GetControllerJobsParams) WithTableName(tableName string) *GetControllerJobsParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the get controller jobs params
func (o *GetControllerJobsParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WithType adds the typeVar to the get controller jobs params
func (o *GetControllerJobsParams) WithType(typeVar *string) *GetControllerJobsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get controller jobs params
func (o *GetControllerJobsParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetControllerJobsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.JobTypes != nil {

		// query param jobTypes
		var qrJobTypes string

		if o.JobTypes != nil {
			qrJobTypes = *o.JobTypes
		}
		qJobTypes := qrJobTypes
		if qJobTypes != "" {

			if err := r.SetQueryParam("jobTypes", qJobTypes); err != nil {
				return err
			}
		}
	}

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
