// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"startree.ai/cli/models"
)

// GetExternalViewReader is a Reader for the GetExternalView structure.
type GetExternalViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetExternalViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetExternalViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetExternalViewOK creates a GetExternalViewOK with default headers values
func NewGetExternalViewOK() *GetExternalViewOK {
	return &GetExternalViewOK{}
}

/*
GetExternalViewOK describes a response with status code 200, with default header values.

successful operation
*/
type GetExternalViewOK struct {
	Payload *models.TableView
}

// IsSuccess returns true when this get external view o k response has a 2xx status code
func (o *GetExternalViewOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get external view o k response has a 3xx status code
func (o *GetExternalViewOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get external view o k response has a 4xx status code
func (o *GetExternalViewOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get external view o k response has a 5xx status code
func (o *GetExternalViewOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get external view o k response a status code equal to that given
func (o *GetExternalViewOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get external view o k response
func (o *GetExternalViewOK) Code() int {
	return 200
}

func (o *GetExternalViewOK) Error() string {
	return fmt.Sprintf("[GET /tables/{tableName}/externalview][%d] getExternalViewOK  %+v", 200, o.Payload)
}

func (o *GetExternalViewOK) String() string {
	return fmt.Sprintf("[GET /tables/{tableName}/externalview][%d] getExternalViewOK  %+v", 200, o.Payload)
}

func (o *GetExternalViewOK) GetPayload() *models.TableView {
	return o.Payload
}

func (o *GetExternalViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TableView)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
