// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetTableStateReader is a Reader for the GetTableState structure.
type GetTableStateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTableStateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTableStateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTableStateOK creates a GetTableStateOK with default headers values
func NewGetTableStateOK() *GetTableStateOK {
	return &GetTableStateOK{}
}

/*
GetTableStateOK describes a response with status code 200, with default header values.

successful operation
*/
type GetTableStateOK struct {
	Payload string
}

// IsSuccess returns true when this get table state o k response has a 2xx status code
func (o *GetTableStateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get table state o k response has a 3xx status code
func (o *GetTableStateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get table state o k response has a 4xx status code
func (o *GetTableStateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get table state o k response has a 5xx status code
func (o *GetTableStateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get table state o k response a status code equal to that given
func (o *GetTableStateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get table state o k response
func (o *GetTableStateOK) Code() int {
	return 200
}

func (o *GetTableStateOK) Error() string {
	return fmt.Sprintf("[GET /tables/{tableName}/state][%d] getTableStateOK  %+v", 200, o.Payload)
}

func (o *GetTableStateOK) String() string {
	return fmt.Sprintf("[GET /tables/{tableName}/state][%d] getTableStateOK  %+v", 200, o.Payload)
}

func (o *GetTableStateOK) GetPayload() string {
	return o.Payload
}

func (o *GetTableStateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
