// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetConsumingSegmentsInfoParams creates a new GetConsumingSegmentsInfoParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetConsumingSegmentsInfoParams() *GetConsumingSegmentsInfoParams {
	return &GetConsumingSegmentsInfoParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetConsumingSegmentsInfoParamsWithTimeout creates a new GetConsumingSegmentsInfoParams object
// with the ability to set a timeout on a request.
func NewGetConsumingSegmentsInfoParamsWithTimeout(timeout time.Duration) *GetConsumingSegmentsInfoParams {
	return &GetConsumingSegmentsInfoParams{
		timeout: timeout,
	}
}

// NewGetConsumingSegmentsInfoParamsWithContext creates a new GetConsumingSegmentsInfoParams object
// with the ability to set a context for a request.
func NewGetConsumingSegmentsInfoParamsWithContext(ctx context.Context) *GetConsumingSegmentsInfoParams {
	return &GetConsumingSegmentsInfoParams{
		Context: ctx,
	}
}

// NewGetConsumingSegmentsInfoParamsWithHTTPClient creates a new GetConsumingSegmentsInfoParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetConsumingSegmentsInfoParamsWithHTTPClient(client *http.Client) *GetConsumingSegmentsInfoParams {
	return &GetConsumingSegmentsInfoParams{
		HTTPClient: client,
	}
}

/*
GetConsumingSegmentsInfoParams contains all the parameters to send to the API endpoint

	for the get consuming segments info operation.

	Typically these are written to a http.Request.
*/
type GetConsumingSegmentsInfoParams struct {

	/* TableName.

	   Realtime table name with or without type
	*/
	TableName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get consuming segments info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetConsumingSegmentsInfoParams) WithDefaults() *GetConsumingSegmentsInfoParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get consuming segments info params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetConsumingSegmentsInfoParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) WithTimeout(timeout time.Duration) *GetConsumingSegmentsInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) WithContext(ctx context.Context) *GetConsumingSegmentsInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) WithHTTPClient(client *http.Client) *GetConsumingSegmentsInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTableName adds the tableName to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) WithTableName(tableName string) *GetConsumingSegmentsInfoParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the get consuming segments info params
func (o *GetConsumingSegmentsInfoParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WriteToRequest writes these params to a swagger request
func (o *GetConsumingSegmentsInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
