// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInstancePartitionsParams creates a new GetInstancePartitionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstancePartitionsParams() *GetInstancePartitionsParams {
	return &GetInstancePartitionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstancePartitionsParamsWithTimeout creates a new GetInstancePartitionsParams object
// with the ability to set a timeout on a request.
func NewGetInstancePartitionsParamsWithTimeout(timeout time.Duration) *GetInstancePartitionsParams {
	return &GetInstancePartitionsParams{
		timeout: timeout,
	}
}

// NewGetInstancePartitionsParamsWithContext creates a new GetInstancePartitionsParams object
// with the ability to set a context for a request.
func NewGetInstancePartitionsParamsWithContext(ctx context.Context) *GetInstancePartitionsParams {
	return &GetInstancePartitionsParams{
		Context: ctx,
	}
}

// NewGetInstancePartitionsParamsWithHTTPClient creates a new GetInstancePartitionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstancePartitionsParamsWithHTTPClient(client *http.Client) *GetInstancePartitionsParams {
	return &GetInstancePartitionsParams{
		HTTPClient: client,
	}
}

/*
GetInstancePartitionsParams contains all the parameters to send to the API endpoint

	for the get instance partitions operation.

	Typically these are written to a http.Request.
*/
type GetInstancePartitionsParams struct {

	/* TableName.

	   Name of the table
	*/
	TableName string

	/* Type.

	   OFFLINE|CONSUMING|COMPLETED
	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get instance partitions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstancePartitionsParams) WithDefaults() *GetInstancePartitionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get instance partitions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstancePartitionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get instance partitions params
func (o *GetInstancePartitionsParams) WithTimeout(timeout time.Duration) *GetInstancePartitionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get instance partitions params
func (o *GetInstancePartitionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get instance partitions params
func (o *GetInstancePartitionsParams) WithContext(ctx context.Context) *GetInstancePartitionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get instance partitions params
func (o *GetInstancePartitionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get instance partitions params
func (o *GetInstancePartitionsParams) WithHTTPClient(client *http.Client) *GetInstancePartitionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get instance partitions params
func (o *GetInstancePartitionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTableName adds the tableName to the get instance partitions params
func (o *GetInstancePartitionsParams) WithTableName(tableName string) *GetInstancePartitionsParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the get instance partitions params
func (o *GetInstancePartitionsParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WithType adds the typeVar to the get instance partitions params
func (o *GetInstancePartitionsParams) WithType(typeVar *string) *GetInstancePartitionsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get instance partitions params
func (o *GetInstancePartitionsParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstancePartitionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
