// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoveInstancePartitionsParams creates a new RemoveInstancePartitionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveInstancePartitionsParams() *RemoveInstancePartitionsParams {
	return &RemoveInstancePartitionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveInstancePartitionsParamsWithTimeout creates a new RemoveInstancePartitionsParams object
// with the ability to set a timeout on a request.
func NewRemoveInstancePartitionsParamsWithTimeout(timeout time.Duration) *RemoveInstancePartitionsParams {
	return &RemoveInstancePartitionsParams{
		timeout: timeout,
	}
}

// NewRemoveInstancePartitionsParamsWithContext creates a new RemoveInstancePartitionsParams object
// with the ability to set a context for a request.
func NewRemoveInstancePartitionsParamsWithContext(ctx context.Context) *RemoveInstancePartitionsParams {
	return &RemoveInstancePartitionsParams{
		Context: ctx,
	}
}

// NewRemoveInstancePartitionsParamsWithHTTPClient creates a new RemoveInstancePartitionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveInstancePartitionsParamsWithHTTPClient(client *http.Client) *RemoveInstancePartitionsParams {
	return &RemoveInstancePartitionsParams{
		HTTPClient: client,
	}
}

/*
RemoveInstancePartitionsParams contains all the parameters to send to the API endpoint

	for the remove instance partitions operation.

	Typically these are written to a http.Request.
*/
type RemoveInstancePartitionsParams struct {

	/* TableName.

	   Name of the table
	*/
	TableName string

	/* Type.

	   OFFLINE|CONSUMING|COMPLETED
	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove instance partitions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveInstancePartitionsParams) WithDefaults() *RemoveInstancePartitionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove instance partitions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveInstancePartitionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove instance partitions params
func (o *RemoveInstancePartitionsParams) WithTimeout(timeout time.Duration) *RemoveInstancePartitionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove instance partitions params
func (o *RemoveInstancePartitionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove instance partitions params
func (o *RemoveInstancePartitionsParams) WithContext(ctx context.Context) *RemoveInstancePartitionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove instance partitions params
func (o *RemoveInstancePartitionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove instance partitions params
func (o *RemoveInstancePartitionsParams) WithHTTPClient(client *http.Client) *RemoveInstancePartitionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove instance partitions params
func (o *RemoveInstancePartitionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTableName adds the tableName to the remove instance partitions params
func (o *RemoveInstancePartitionsParams) WithTableName(tableName string) *RemoveInstancePartitionsParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the remove instance partitions params
func (o *RemoveInstancePartitionsParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WithType adds the typeVar to the remove instance partitions params
func (o *RemoveInstancePartitionsParams) WithType(typeVar *string) *RemoveInstancePartitionsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the remove instance partitions params
func (o *RemoveInstancePartitionsParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveInstancePartitionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
