// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateIndexingConfigParams creates a new UpdateIndexingConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateIndexingConfigParams() *UpdateIndexingConfigParams {
	return &UpdateIndexingConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateIndexingConfigParamsWithTimeout creates a new UpdateIndexingConfigParams object
// with the ability to set a timeout on a request.
func NewUpdateIndexingConfigParamsWithTimeout(timeout time.Duration) *UpdateIndexingConfigParams {
	return &UpdateIndexingConfigParams{
		timeout: timeout,
	}
}

// NewUpdateIndexingConfigParamsWithContext creates a new UpdateIndexingConfigParams object
// with the ability to set a context for a request.
func NewUpdateIndexingConfigParamsWithContext(ctx context.Context) *UpdateIndexingConfigParams {
	return &UpdateIndexingConfigParams{
		Context: ctx,
	}
}

// NewUpdateIndexingConfigParamsWithHTTPClient creates a new UpdateIndexingConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateIndexingConfigParamsWithHTTPClient(client *http.Client) *UpdateIndexingConfigParams {
	return &UpdateIndexingConfigParams{
		HTTPClient: client,
	}
}

/*
UpdateIndexingConfigParams contains all the parameters to send to the API endpoint

	for the update indexing config operation.

	Typically these are written to a http.Request.
*/
type UpdateIndexingConfigParams struct {

	// Body.
	Body string

	/* TableName.

	   Table name (without type)
	*/
	TableName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update indexing config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateIndexingConfigParams) WithDefaults() *UpdateIndexingConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update indexing config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateIndexingConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update indexing config params
func (o *UpdateIndexingConfigParams) WithTimeout(timeout time.Duration) *UpdateIndexingConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update indexing config params
func (o *UpdateIndexingConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update indexing config params
func (o *UpdateIndexingConfigParams) WithContext(ctx context.Context) *UpdateIndexingConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update indexing config params
func (o *UpdateIndexingConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update indexing config params
func (o *UpdateIndexingConfigParams) WithHTTPClient(client *http.Client) *UpdateIndexingConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update indexing config params
func (o *UpdateIndexingConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update indexing config params
func (o *UpdateIndexingConfigParams) WithBody(body string) *UpdateIndexingConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update indexing config params
func (o *UpdateIndexingConfigParams) SetBody(body string) {
	o.Body = body
}

// WithTableName adds the tableName to the update indexing config params
func (o *UpdateIndexingConfigParams) WithTableName(tableName string) *UpdateIndexingConfigParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the update indexing config params
func (o *UpdateIndexingConfigParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateIndexingConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
