// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUpdateConfigParams creates a new UpdateConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateConfigParams() *UpdateConfigParams {
	return &UpdateConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateConfigParamsWithTimeout creates a new UpdateConfigParams object
// with the ability to set a timeout on a request.
func NewUpdateConfigParamsWithTimeout(timeout time.Duration) *UpdateConfigParams {
	return &UpdateConfigParams{
		timeout: timeout,
	}
}

// NewUpdateConfigParamsWithContext creates a new UpdateConfigParams object
// with the ability to set a context for a request.
func NewUpdateConfigParamsWithContext(ctx context.Context) *UpdateConfigParams {
	return &UpdateConfigParams{
		Context: ctx,
	}
}

// NewUpdateConfigParamsWithHTTPClient creates a new UpdateConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateConfigParamsWithHTTPClient(client *http.Client) *UpdateConfigParams {
	return &UpdateConfigParams{
		HTTPClient: client,
	}
}

/*
UpdateConfigParams contains all the parameters to send to the API endpoint

	for the update config operation.

	Typically these are written to a http.Request.
*/
type UpdateConfigParams struct {

	// Body.
	Body string

	/* Reload.

	   Reload the table if the new schema is backward compatible
	*/
	Reload *bool

	/* TableName.

	   TableConfigs name i.e. raw table name
	*/
	TableName string

	/* ValidationTypesToSkip.

	   comma separated list of validation type(s) to skip. supported types: (ALL|TASK|UPSERT)
	*/
	ValidationTypesToSkip *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateConfigParams) WithDefaults() *UpdateConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateConfigParams) SetDefaults() {
	var (
		reloadDefault = bool(false)
	)

	val := UpdateConfigParams{
		Reload: &reloadDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the update config params
func (o *UpdateConfigParams) WithTimeout(timeout time.Duration) *UpdateConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update config params
func (o *UpdateConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update config params
func (o *UpdateConfigParams) WithContext(ctx context.Context) *UpdateConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update config params
func (o *UpdateConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update config params
func (o *UpdateConfigParams) WithHTTPClient(client *http.Client) *UpdateConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update config params
func (o *UpdateConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update config params
func (o *UpdateConfigParams) WithBody(body string) *UpdateConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update config params
func (o *UpdateConfigParams) SetBody(body string) {
	o.Body = body
}

// WithReload adds the reload to the update config params
func (o *UpdateConfigParams) WithReload(reload *bool) *UpdateConfigParams {
	o.SetReload(reload)
	return o
}

// SetReload adds the reload to the update config params
func (o *UpdateConfigParams) SetReload(reload *bool) {
	o.Reload = reload
}

// WithTableName adds the tableName to the update config params
func (o *UpdateConfigParams) WithTableName(tableName string) *UpdateConfigParams {
	o.SetTableName(tableName)
	return o
}

// SetTableName adds the tableName to the update config params
func (o *UpdateConfigParams) SetTableName(tableName string) {
	o.TableName = tableName
}

// WithValidationTypesToSkip adds the validationTypesToSkip to the update config params
func (o *UpdateConfigParams) WithValidationTypesToSkip(validationTypesToSkip *string) *UpdateConfigParams {
	o.SetValidationTypesToSkip(validationTypesToSkip)
	return o
}

// SetValidationTypesToSkip adds the validationTypesToSkip to the update config params
func (o *UpdateConfigParams) SetValidationTypesToSkip(validationTypesToSkip *string) {
	o.ValidationTypesToSkip = validationTypesToSkip
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.Reload != nil {

		// query param reload
		var qrReload bool

		if o.Reload != nil {
			qrReload = *o.Reload
		}
		qReload := swag.FormatBool(qrReload)
		if qReload != "" {

			if err := r.SetQueryParam("reload", qReload); err != nil {
				return err
			}
		}
	}

	// path param tableName
	if err := r.SetPathParam("tableName", o.TableName); err != nil {
		return err
	}

	if o.ValidationTypesToSkip != nil {

		// query param validationTypesToSkip
		var qrValidationTypesToSkip string

		if o.ValidationTypesToSkip != nil {
			qrValidationTypesToSkip = *o.ValidationTypesToSkip
		}
		qValidationTypesToSkip := qrValidationTypesToSkip
		if qValidationTypesToSkip != "" {

			if err := r.SetQueryParam("validationTypesToSkip", qValidationTypesToSkip); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
