// Code generated by go-swagger; DO NOT EDIT.

package table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ValidateConfigReader is a Reader for the ValidateConfig structure.
type ValidateConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewValidateConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewValidateConfigOK creates a ValidateConfigOK with default headers values
func NewValidateConfigOK() *ValidateConfigOK {
	return &ValidateConfigOK{}
}

/*
ValidateConfigOK describes a response with status code 200, with default header values.

successful operation
*/
type ValidateConfigOK struct {
	Payload string
}

// IsSuccess returns true when this validate config o k response has a 2xx status code
func (o *ValidateConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this validate config o k response has a 3xx status code
func (o *ValidateConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this validate config o k response has a 4xx status code
func (o *ValidateConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this validate config o k response has a 5xx status code
func (o *ValidateConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this validate config o k response a status code equal to that given
func (o *ValidateConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the validate config o k response
func (o *ValidateConfigOK) Code() int {
	return 200
}

func (o *ValidateConfigOK) Error() string {
	return fmt.Sprintf("[POST /tableConfigs/validate][%d] validateConfigOK  %+v", 200, o.Payload)
}

func (o *ValidateConfigOK) String() string {
	return fmt.Sprintf("[POST /tableConfigs/validate][%d] validateConfigOK  %+v", 200, o.Payload)
}

func (o *ValidateConfigOK) GetPayload() string {
	return o.Payload
}

func (o *ValidateConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
