// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UpdateClusterConfigReader is a Reader for the UpdateClusterConfig structure.
type UpdateClusterConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateClusterConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateClusterConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewUpdateClusterConfigInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateClusterConfigOK creates a UpdateClusterConfigOK with default headers values
func NewUpdateClusterConfigOK() *UpdateClusterConfigOK {
	return &UpdateClusterConfigOK{}
}

/*
UpdateClusterConfigOK describes a response with status code 200, with default header values.

Success
*/
type UpdateClusterConfigOK struct {
}

// IsSuccess returns true when this update cluster config o k response has a 2xx status code
func (o *UpdateClusterConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update cluster config o k response has a 3xx status code
func (o *UpdateClusterConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update cluster config o k response has a 4xx status code
func (o *UpdateClusterConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update cluster config o k response has a 5xx status code
func (o *UpdateClusterConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update cluster config o k response a status code equal to that given
func (o *UpdateClusterConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update cluster config o k response
func (o *UpdateClusterConfigOK) Code() int {
	return 200
}

func (o *UpdateClusterConfigOK) Error() string {
	return fmt.Sprintf("[POST /cluster/configs][%d] updateClusterConfigOK ", 200)
}

func (o *UpdateClusterConfigOK) String() string {
	return fmt.Sprintf("[POST /cluster/configs][%d] updateClusterConfigOK ", 200)
}

func (o *UpdateClusterConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateClusterConfigInternalServerError creates a UpdateClusterConfigInternalServerError with default headers values
func NewUpdateClusterConfigInternalServerError() *UpdateClusterConfigInternalServerError {
	return &UpdateClusterConfigInternalServerError{}
}

/*
UpdateClusterConfigInternalServerError describes a response with status code 500, with default header values.

Server error updating configuration
*/
type UpdateClusterConfigInternalServerError struct {
}

// IsSuccess returns true when this update cluster config internal server error response has a 2xx status code
func (o *UpdateClusterConfigInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update cluster config internal server error response has a 3xx status code
func (o *UpdateClusterConfigInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update cluster config internal server error response has a 4xx status code
func (o *UpdateClusterConfigInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update cluster config internal server error response has a 5xx status code
func (o *UpdateClusterConfigInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update cluster config internal server error response a status code equal to that given
func (o *UpdateClusterConfigInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the update cluster config internal server error response
func (o *UpdateClusterConfigInternalServerError) Code() int {
	return 500
}

func (o *UpdateClusterConfigInternalServerError) Error() string {
	return fmt.Sprintf("[POST /cluster/configs][%d] updateClusterConfigInternalServerError ", 500)
}

func (o *UpdateClusterConfigInternalServerError) String() string {
	return fmt.Sprintf("[POST /cluster/configs][%d] updateClusterConfigInternalServerError ", 500)
}

func (o *UpdateClusterConfigInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
