// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/spf13/cobra"
	"startree.ai/cli/models"
)

// Schema cli for ConfigSuccessResponse

// register flags to command
func registerModelConfigSuccessResponseFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerConfigSuccessResponseStatus(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerConfigSuccessResponseUnrecognizedProperties(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerConfigSuccessResponseStatus(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	statusDescription := ``

	var statusFlagName string
	if cmdPrefix == "" {
		statusFlagName = "status"
	} else {
		statusFlagName = fmt.Sprintf("%v.status", cmdPrefix)
	}

	var statusFlagDefault string

	_ = cmd.PersistentFlags().String(statusFlagName, statusFlagDefault, statusDescription)

	return nil
}

func registerConfigSuccessResponseUnrecognizedProperties(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: unrecognizedProperties map[string]interface{} map type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelConfigSuccessResponseFlags(depth int, m *models.ConfigSuccessResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, statusAdded := retrieveConfigSuccessResponseStatusFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || statusAdded

	err, unrecognizedPropertiesAdded := retrieveConfigSuccessResponseUnrecognizedPropertiesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || unrecognizedPropertiesAdded

	return nil, retAdded
}

func retrieveConfigSuccessResponseStatusFlags(depth int, m *models.ConfigSuccessResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	statusFlagName := fmt.Sprintf("%v.status", cmdPrefix)
	if cmd.Flags().Changed(statusFlagName) {

		var statusFlagName string
		if cmdPrefix == "" {
			statusFlagName = "status"
		} else {
			statusFlagName = fmt.Sprintf("%v.status", cmdPrefix)
		}

		statusFlagValue, err := cmd.Flags().GetString(statusFlagName)
		if err != nil {
			return err, false
		}
		m.Status = statusFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveConfigSuccessResponseUnrecognizedPropertiesFlags(depth int, m *models.ConfigSuccessResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	unrecognizedPropertiesFlagName := fmt.Sprintf("%v.unrecognizedProperties", cmdPrefix)
	if cmd.Flags().Changed(unrecognizedPropertiesFlagName) {
		// warning: unrecognizedProperties map type map[string]interface{} is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
