// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"startree.ai/cli/client/task"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationTaskDeleteTaskMetadataByTableCmd returns a cmd to handle operation deleteTaskMetadataByTable
func makeOperationTaskDeleteTaskMetadataByTableCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "deleteTaskMetadataByTable",
		Short: ``,
		RunE:  runOperationTaskDeleteTaskMetadataByTable,
	}

	if err := registerOperationTaskDeleteTaskMetadataByTableParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationTaskDeleteTaskMetadataByTable uses cmd flags to call endpoint api
func runOperationTaskDeleteTaskMetadataByTable(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := task.NewDeleteTaskMetadataByTableParams()
	if err, _ := retrieveOperationTaskDeleteTaskMetadataByTableTableNameWithTypeFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationTaskDeleteTaskMetadataByTableTaskTypeFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationTaskDeleteTaskMetadataByTableResult(appCli.Task.DeleteTaskMetadataByTable(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationTaskDeleteTaskMetadataByTableParamFlags registers all flags needed to fill params
func registerOperationTaskDeleteTaskMetadataByTableParamFlags(cmd *cobra.Command) error {
	if err := registerOperationTaskDeleteTaskMetadataByTableTableNameWithTypeParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationTaskDeleteTaskMetadataByTableTaskTypeParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationTaskDeleteTaskMetadataByTableTableNameWithTypeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	tableNameWithTypeDescription := `Required. Table name with type`

	var tableNameWithTypeFlagName string
	if cmdPrefix == "" {
		tableNameWithTypeFlagName = "tableNameWithType"
	} else {
		tableNameWithTypeFlagName = fmt.Sprintf("%v.tableNameWithType", cmdPrefix)
	}

	var tableNameWithTypeFlagDefault string

	_ = cmd.PersistentFlags().String(tableNameWithTypeFlagName, tableNameWithTypeFlagDefault, tableNameWithTypeDescription)

	return nil
}
func registerOperationTaskDeleteTaskMetadataByTableTaskTypeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	taskTypeDescription := `Required. Task type`

	var taskTypeFlagName string
	if cmdPrefix == "" {
		taskTypeFlagName = "taskType"
	} else {
		taskTypeFlagName = fmt.Sprintf("%v.taskType", cmdPrefix)
	}

	var taskTypeFlagDefault string

	_ = cmd.PersistentFlags().String(taskTypeFlagName, taskTypeFlagDefault, taskTypeDescription)

	return nil
}

func retrieveOperationTaskDeleteTaskMetadataByTableTableNameWithTypeFlag(m *task.DeleteTaskMetadataByTableParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("tableNameWithType") {

		var tableNameWithTypeFlagName string
		if cmdPrefix == "" {
			tableNameWithTypeFlagName = "tableNameWithType"
		} else {
			tableNameWithTypeFlagName = fmt.Sprintf("%v.tableNameWithType", cmdPrefix)
		}

		tableNameWithTypeFlagValue, err := cmd.Flags().GetString(tableNameWithTypeFlagName)
		if err != nil {
			return err, false
		}
		m.TableNameWithType = tableNameWithTypeFlagValue

	}
	return nil, retAdded
}
func retrieveOperationTaskDeleteTaskMetadataByTableTaskTypeFlag(m *task.DeleteTaskMetadataByTableParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("taskType") {

		var taskTypeFlagName string
		if cmdPrefix == "" {
			taskTypeFlagName = "taskType"
		} else {
			taskTypeFlagName = fmt.Sprintf("%v.taskType", cmdPrefix)
		}

		taskTypeFlagValue, err := cmd.Flags().GetString(taskTypeFlagName)
		if err != nil {
			return err, false
		}
		m.TaskType = taskTypeFlagValue

	}
	return nil, retAdded
}

// parseOperationTaskDeleteTaskMetadataByTableResult parses request result and return the string content
func parseOperationTaskDeleteTaskMetadataByTableResult(resp0 *task.DeleteTaskMetadataByTableOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*task.DeleteTaskMetadataByTableOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
