// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"startree.ai/cli/client/table"

	"github.com/spf13/cobra"
)

// makeOperationTableGetLiveBrokersForTableCmd returns a cmd to handle operation getLiveBrokersForTable
func makeOperationTableGetLiveBrokersForTableCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getLiveBrokersForTable",
		Short: `List live brokers of the given table based on EV`,
		RunE:  runOperationTableGetLiveBrokersForTable,
	}

	if err := registerOperationTableGetLiveBrokersForTableParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationTableGetLiveBrokersForTable uses cmd flags to call endpoint api
func runOperationTableGetLiveBrokersForTable(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := table.NewGetLiveBrokersForTableParams()
	if err, _ := retrieveOperationTableGetLiveBrokersForTableTableNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationTableGetLiveBrokersForTableResult(appCli.Table.GetLiveBrokersForTable(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationTableGetLiveBrokersForTableParamFlags registers all flags needed to fill params
func registerOperationTableGetLiveBrokersForTableParamFlags(cmd *cobra.Command) error {
	if err := registerOperationTableGetLiveBrokersForTableTableNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationTableGetLiveBrokersForTableTableNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	tableNameDescription := `Required. Table name (with or without type)`

	var tableNameFlagName string
	if cmdPrefix == "" {
		tableNameFlagName = "tableName"
	} else {
		tableNameFlagName = fmt.Sprintf("%v.tableName", cmdPrefix)
	}

	var tableNameFlagDefault string

	_ = cmd.PersistentFlags().String(tableNameFlagName, tableNameFlagDefault, tableNameDescription)

	return nil
}

func retrieveOperationTableGetLiveBrokersForTableTableNameFlag(m *table.GetLiveBrokersForTableParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("tableName") {

		var tableNameFlagName string
		if cmdPrefix == "" {
			tableNameFlagName = "tableName"
		} else {
			tableNameFlagName = fmt.Sprintf("%v.tableName", cmdPrefix)
		}

		tableNameFlagValue, err := cmd.Flags().GetString(tableNameFlagName)
		if err != nil {
			return err, false
		}
		m.TableName = tableNameFlagValue

	}
	return nil, retAdded
}

// parseOperationTableGetLiveBrokersForTableResult parses request result and return the string content
func parseOperationTableGetLiveBrokersForTableResult(resp0 *table.GetLiveBrokersForTableOK, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning getLiveBrokersForTableOK is not supported

		// Non schema case: warning getLiveBrokersForTableNotFound is not supported

		// Non schema case: warning getLiveBrokersForTableInternalServerError is not supported

		return "", respErr
	}

	// warning: non schema response getLiveBrokersForTableOK is not supported by go-swagger cli yet.

	return "", nil
}
