// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"startree.ai/cli/client/segment"

	"github.com/spf13/cobra"
)

// makeOperationSegmentGetSegmentTiersCmd returns a cmd to handle operation getSegmentTiers
func makeOperationSegmentGetSegmentTiersCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getSegmentTiers",
		Short: `Get storage tiers for the given segment`,
		RunE:  runOperationSegmentGetSegmentTiers,
	}

	if err := registerOperationSegmentGetSegmentTiersParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationSegmentGetSegmentTiers uses cmd flags to call endpoint api
func runOperationSegmentGetSegmentTiers(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := segment.NewGetSegmentTiersParams()
	if err, _ := retrieveOperationSegmentGetSegmentTiersSegmentNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationSegmentGetSegmentTiersTableNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationSegmentGetSegmentTiersTypeFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationSegmentGetSegmentTiersResult(appCli.Segment.GetSegmentTiers(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationSegmentGetSegmentTiersParamFlags registers all flags needed to fill params
func registerOperationSegmentGetSegmentTiersParamFlags(cmd *cobra.Command) error {
	if err := registerOperationSegmentGetSegmentTiersSegmentNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSegmentGetSegmentTiersTableNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSegmentGetSegmentTiersTypeParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationSegmentGetSegmentTiersSegmentNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	segmentNameDescription := `Required. Name of the segment`

	var segmentNameFlagName string
	if cmdPrefix == "" {
		segmentNameFlagName = "segmentName"
	} else {
		segmentNameFlagName = fmt.Sprintf("%v.segmentName", cmdPrefix)
	}

	var segmentNameFlagDefault string

	_ = cmd.PersistentFlags().String(segmentNameFlagName, segmentNameFlagDefault, segmentNameDescription)

	return nil
}
func registerOperationSegmentGetSegmentTiersTableNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	tableNameDescription := `Required. Name of the table`

	var tableNameFlagName string
	if cmdPrefix == "" {
		tableNameFlagName = "tableName"
	} else {
		tableNameFlagName = fmt.Sprintf("%v.tableName", cmdPrefix)
	}

	var tableNameFlagDefault string

	_ = cmd.PersistentFlags().String(tableNameFlagName, tableNameFlagDefault, tableNameDescription)

	return nil
}
func registerOperationSegmentGetSegmentTiersTypeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	typeDescription := `Required. OFFLINE|REALTIME`

	var typeFlagName string
	if cmdPrefix == "" {
		typeFlagName = "type"
	} else {
		typeFlagName = fmt.Sprintf("%v.type", cmdPrefix)
	}

	var typeFlagDefault string

	_ = cmd.PersistentFlags().String(typeFlagName, typeFlagDefault, typeDescription)

	return nil
}

func retrieveOperationSegmentGetSegmentTiersSegmentNameFlag(m *segment.GetSegmentTiersParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("segmentName") {

		var segmentNameFlagName string
		if cmdPrefix == "" {
			segmentNameFlagName = "segmentName"
		} else {
			segmentNameFlagName = fmt.Sprintf("%v.segmentName", cmdPrefix)
		}

		segmentNameFlagValue, err := cmd.Flags().GetString(segmentNameFlagName)
		if err != nil {
			return err, false
		}
		m.SegmentName = segmentNameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationSegmentGetSegmentTiersTableNameFlag(m *segment.GetSegmentTiersParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("tableName") {

		var tableNameFlagName string
		if cmdPrefix == "" {
			tableNameFlagName = "tableName"
		} else {
			tableNameFlagName = fmt.Sprintf("%v.tableName", cmdPrefix)
		}

		tableNameFlagValue, err := cmd.Flags().GetString(tableNameFlagName)
		if err != nil {
			return err, false
		}
		m.TableName = tableNameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationSegmentGetSegmentTiersTypeFlag(m *segment.GetSegmentTiersParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("type") {

		var typeFlagName string
		if cmdPrefix == "" {
			typeFlagName = "type"
		} else {
			typeFlagName = fmt.Sprintf("%v.type", cmdPrefix)
		}

		typeFlagValue, err := cmd.Flags().GetString(typeFlagName)
		if err != nil {
			return err, false
		}
		m.Type = typeFlagValue

	}
	return nil, retAdded
}

// parseOperationSegmentGetSegmentTiersResult parses request result and return the string content
func parseOperationSegmentGetSegmentTiersResult(resp0 *segment.GetSegmentTiersOK, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning getSegmentTiersOK is not supported

		// Non schema case: warning getSegmentTiersNotFound is not supported

		// Non schema case: warning getSegmentTiersInternalServerError is not supported

		return "", respErr
	}

	// warning: non schema response getSegmentTiersOK is not supported by go-swagger cli yet.

	return "", nil
}
