// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"startree.ai/cli/client/task"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationTaskGetTaskStateDeprecatedCmd returns a cmd to handle operation getTaskStateDeprecated
func makeOperationTaskGetTaskStateDeprecatedCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getTaskStateDeprecated",
		Short: ``,
		RunE:  runOperationTaskGetTaskStateDeprecated,
	}

	if err := registerOperationTaskGetTaskStateDeprecatedParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationTaskGetTaskStateDeprecated uses cmd flags to call endpoint api
func runOperationTaskGetTaskStateDeprecated(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := task.NewGetTaskStateDeprecatedParams()
	if err, _ := retrieveOperationTaskGetTaskStateDeprecatedTaskNameFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationTaskGetTaskStateDeprecatedResult(appCli.Task.GetTaskStateDeprecated(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationTaskGetTaskStateDeprecatedParamFlags registers all flags needed to fill params
func registerOperationTaskGetTaskStateDeprecatedParamFlags(cmd *cobra.Command) error {
	if err := registerOperationTaskGetTaskStateDeprecatedTaskNameParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationTaskGetTaskStateDeprecatedTaskNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	taskNameDescription := `Required. Task name`

	var taskNameFlagName string
	if cmdPrefix == "" {
		taskNameFlagName = "taskName"
	} else {
		taskNameFlagName = fmt.Sprintf("%v.taskName", cmdPrefix)
	}

	var taskNameFlagDefault string

	_ = cmd.PersistentFlags().String(taskNameFlagName, taskNameFlagDefault, taskNameDescription)

	return nil
}

func retrieveOperationTaskGetTaskStateDeprecatedTaskNameFlag(m *task.GetTaskStateDeprecatedParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("taskName") {

		var taskNameFlagName string
		if cmdPrefix == "" {
			taskNameFlagName = "taskName"
		} else {
			taskNameFlagName = fmt.Sprintf("%v.taskName", cmdPrefix)
		}

		taskNameFlagValue, err := cmd.Flags().GetString(taskNameFlagName)
		if err != nil {
			return err, false
		}
		m.TaskName = taskNameFlagValue

	}
	return nil, retAdded
}

// parseOperationTaskGetTaskStateDeprecatedResult parses request result and return the string content
func parseOperationTaskGetTaskStateDeprecatedResult(resp0 *task.GetTaskStateDeprecatedOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*task.GetTaskStateDeprecatedOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
