// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"startree.ai/cli/client/version"

	"github.com/spf13/cobra"
)

// makeOperationVersionGetVersionNumberCmd returns a cmd to handle operation getVersionNumber
func makeOperationVersionGetVersionNumberCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "getVersionNumber",
		Short: ``,
		RunE:  runOperationVersionGetVersionNumber,
	}

	if err := registerOperationVersionGetVersionNumberParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationVersionGetVersionNumber uses cmd flags to call endpoint api
func runOperationVersionGetVersionNumber(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := version.NewGetVersionNumberParams()
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationVersionGetVersionNumberResult(appCli.Version.GetVersionNumber(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationVersionGetVersionNumberParamFlags registers all flags needed to fill params
func registerOperationVersionGetVersionNumberParamFlags(cmd *cobra.Command) error {
	return nil
}

// parseOperationVersionGetVersionNumberResult parses request result and return the string content
func parseOperationVersionGetVersionNumberResult(resp0 *version.GetVersionNumberOK, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning getVersionNumberOK is not supported

		return "", respErr
	}

	// warning: non schema response getVersionNumberOK is not supported by go-swagger cli yet.

	return "", nil
}
