// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"startree.ai/cli/client/table"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationTableListConfigsCmd returns a cmd to handle operation listConfigs
func makeOperationTableListConfigsCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "listConfigs",
		Short: `Lists all TableConfigs in cluster`,
		RunE:  runOperationTableListConfigs,
	}

	if err := registerOperationTableListConfigsParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationTableListConfigs uses cmd flags to call endpoint api
func runOperationTableListConfigs(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := table.NewListConfigsParams()
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationTableListConfigsResult(appCli.Table.ListConfigs(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationTableListConfigsParamFlags registers all flags needed to fill params
func registerOperationTableListConfigsParamFlags(cmd *cobra.Command) error {
	return nil
}

// parseOperationTableListConfigsResult parses request result and return the string content
func parseOperationTableListConfigsResult(resp0 *table.ListConfigsOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*table.ListConfigsOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr := fmt.Sprintf("%v", resp0.Payload)
		return string(msgStr), nil
	}

	return "", nil
}
