// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"startree.ai/cli/client/segment"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationSegmentReloadAllSegmentsDeprecated2Cmd returns a cmd to handle operation reloadAllSegmentsDeprecated2
func makeOperationSegmentReloadAllSegmentsDeprecated2Cmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "reloadAllSegmentsDeprecated2",
		Short: `Reload all segments (deprecated, use 'POST /segments/{tableName}/reload' instead)`,
		RunE:  runOperationSegmentReloadAllSegmentsDeprecated2,
	}

	if err := registerOperationSegmentReloadAllSegmentsDeprecated2ParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationSegmentReloadAllSegmentsDeprecated2 uses cmd flags to call endpoint api
func runOperationSegmentReloadAllSegmentsDeprecated2(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := segment.NewReloadAllSegmentsDeprecated2Params()
	if err, _ := retrieveOperationSegmentReloadAllSegmentsDeprecated2TableNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationSegmentReloadAllSegmentsDeprecated2TypeFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationSegmentReloadAllSegmentsDeprecated2Result(appCli.Segment.ReloadAllSegmentsDeprecated2(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationSegmentReloadAllSegmentsDeprecated2ParamFlags registers all flags needed to fill params
func registerOperationSegmentReloadAllSegmentsDeprecated2ParamFlags(cmd *cobra.Command) error {
	if err := registerOperationSegmentReloadAllSegmentsDeprecated2TableNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSegmentReloadAllSegmentsDeprecated2TypeParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationSegmentReloadAllSegmentsDeprecated2TableNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	tableNameDescription := `Required. Name of the table`

	var tableNameFlagName string
	if cmdPrefix == "" {
		tableNameFlagName = "tableName"
	} else {
		tableNameFlagName = fmt.Sprintf("%v.tableName", cmdPrefix)
	}

	var tableNameFlagDefault string

	_ = cmd.PersistentFlags().String(tableNameFlagName, tableNameFlagDefault, tableNameDescription)

	return nil
}
func registerOperationSegmentReloadAllSegmentsDeprecated2TypeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	typeDescription := `OFFLINE|REALTIME`

	var typeFlagName string
	if cmdPrefix == "" {
		typeFlagName = "type"
	} else {
		typeFlagName = fmt.Sprintf("%v.type", cmdPrefix)
	}

	var typeFlagDefault string

	_ = cmd.PersistentFlags().String(typeFlagName, typeFlagDefault, typeDescription)

	return nil
}

func retrieveOperationSegmentReloadAllSegmentsDeprecated2TableNameFlag(m *segment.ReloadAllSegmentsDeprecated2Params, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("tableName") {

		var tableNameFlagName string
		if cmdPrefix == "" {
			tableNameFlagName = "tableName"
		} else {
			tableNameFlagName = fmt.Sprintf("%v.tableName", cmdPrefix)
		}

		tableNameFlagValue, err := cmd.Flags().GetString(tableNameFlagName)
		if err != nil {
			return err, false
		}
		m.TableName = tableNameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationSegmentReloadAllSegmentsDeprecated2TypeFlag(m *segment.ReloadAllSegmentsDeprecated2Params, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("type") {

		var typeFlagName string
		if cmdPrefix == "" {
			typeFlagName = "type"
		} else {
			typeFlagName = fmt.Sprintf("%v.type", cmdPrefix)
		}

		typeFlagValue, err := cmd.Flags().GetString(typeFlagName)
		if err != nil {
			return err, false
		}
		m.Type = &typeFlagValue

	}
	return nil, retAdded
}

// parseOperationSegmentReloadAllSegmentsDeprecated2Result parses request result and return the string content
func parseOperationSegmentReloadAllSegmentsDeprecated2Result(resp0 *segment.ReloadAllSegmentsDeprecated2OK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*segment.ReloadAllSegmentsDeprecated2OK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
