// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"startree.ai/cli/client/table"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationTableRemoveInstancePartitionsCmd returns a cmd to handle operation removeInstancePartitions
func makeOperationTableRemoveInstancePartitionsCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "removeInstancePartitions",
		Short: ``,
		RunE:  runOperationTableRemoveInstancePartitions,
	}

	if err := registerOperationTableRemoveInstancePartitionsParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationTableRemoveInstancePartitions uses cmd flags to call endpoint api
func runOperationTableRemoveInstancePartitions(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := table.NewRemoveInstancePartitionsParams()
	if err, _ := retrieveOperationTableRemoveInstancePartitionsTableNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationTableRemoveInstancePartitionsTypeFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationTableRemoveInstancePartitionsResult(appCli.Table.RemoveInstancePartitions(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationTableRemoveInstancePartitionsParamFlags registers all flags needed to fill params
func registerOperationTableRemoveInstancePartitionsParamFlags(cmd *cobra.Command) error {
	if err := registerOperationTableRemoveInstancePartitionsTableNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationTableRemoveInstancePartitionsTypeParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationTableRemoveInstancePartitionsTableNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	tableNameDescription := `Required. Name of the table`

	var tableNameFlagName string
	if cmdPrefix == "" {
		tableNameFlagName = "tableName"
	} else {
		tableNameFlagName = fmt.Sprintf("%v.tableName", cmdPrefix)
	}

	var tableNameFlagDefault string

	_ = cmd.PersistentFlags().String(tableNameFlagName, tableNameFlagDefault, tableNameDescription)

	return nil
}
func registerOperationTableRemoveInstancePartitionsTypeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	typeDescription := `Enum: ["OFFLINE","CONSUMING","COMPLETED"]. OFFLINE|CONSUMING|COMPLETED`

	var typeFlagName string
	if cmdPrefix == "" {
		typeFlagName = "type"
	} else {
		typeFlagName = fmt.Sprintf("%v.type", cmdPrefix)
	}

	var typeFlagDefault string

	_ = cmd.PersistentFlags().String(typeFlagName, typeFlagDefault, typeDescription)

	if err := cmd.RegisterFlagCompletionFunc(typeFlagName,
		func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
			var res []string
			if err := json.Unmarshal([]byte(`["OFFLINE","CONSUMING","COMPLETED"]`), &res); err != nil {
				panic(err)
			}
			return res, cobra.ShellCompDirectiveDefault
		}); err != nil {
		return err
	}

	return nil
}

func retrieveOperationTableRemoveInstancePartitionsTableNameFlag(m *table.RemoveInstancePartitionsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("tableName") {

		var tableNameFlagName string
		if cmdPrefix == "" {
			tableNameFlagName = "tableName"
		} else {
			tableNameFlagName = fmt.Sprintf("%v.tableName", cmdPrefix)
		}

		tableNameFlagValue, err := cmd.Flags().GetString(tableNameFlagName)
		if err != nil {
			return err, false
		}
		m.TableName = tableNameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationTableRemoveInstancePartitionsTypeFlag(m *table.RemoveInstancePartitionsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("type") {

		var typeFlagName string
		if cmdPrefix == "" {
			typeFlagName = "type"
		} else {
			typeFlagName = fmt.Sprintf("%v.type", cmdPrefix)
		}

		typeFlagValue, err := cmd.Flags().GetString(typeFlagName)
		if err != nil {
			return err, false
		}
		m.Type = &typeFlagValue

	}
	return nil, retAdded
}

// parseOperationTableRemoveInstancePartitionsResult parses request result and return the string content
func parseOperationTableRemoveInstancePartitionsResult(resp0 *table.RemoveInstancePartitionsOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*table.RemoveInstancePartitionsOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
