// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"startree.ai/cli/client/segment"

	"github.com/spf13/cobra"
)

// makeOperationSegmentRevertReplaceSegmentsCmd returns a cmd to handle operation revertReplaceSegments
func makeOperationSegmentRevertReplaceSegmentsCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "revertReplaceSegments",
		Short: `Revert segments replacement`,
		RunE:  runOperationSegmentRevertReplaceSegments,
	}

	if err := registerOperationSegmentRevertReplaceSegmentsParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationSegmentRevertReplaceSegments uses cmd flags to call endpoint api
func runOperationSegmentRevertReplaceSegments(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := segment.NewRevertReplaceSegmentsParams()
	if err, _ := retrieveOperationSegmentRevertReplaceSegmentsForceRevertFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationSegmentRevertReplaceSegmentsSegmentLineageEntryIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationSegmentRevertReplaceSegmentsTableNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationSegmentRevertReplaceSegmentsTypeFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationSegmentRevertReplaceSegmentsResult(appCli.Segment.RevertReplaceSegments(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationSegmentRevertReplaceSegmentsParamFlags registers all flags needed to fill params
func registerOperationSegmentRevertReplaceSegmentsParamFlags(cmd *cobra.Command) error {
	if err := registerOperationSegmentRevertReplaceSegmentsForceRevertParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSegmentRevertReplaceSegmentsSegmentLineageEntryIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSegmentRevertReplaceSegmentsTableNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationSegmentRevertReplaceSegmentsTypeParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationSegmentRevertReplaceSegmentsForceRevertParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	forceRevertDescription := `Force revert in case the user knows that the lineage entry is interrupted`

	var forceRevertFlagName string
	if cmdPrefix == "" {
		forceRevertFlagName = "forceRevert"
	} else {
		forceRevertFlagName = fmt.Sprintf("%v.forceRevert", cmdPrefix)
	}

	var forceRevertFlagDefault bool

	_ = cmd.PersistentFlags().Bool(forceRevertFlagName, forceRevertFlagDefault, forceRevertDescription)

	return nil
}
func registerOperationSegmentRevertReplaceSegmentsSegmentLineageEntryIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	segmentLineageEntryIdDescription := `Required. Segment lineage entry id to revert`

	var segmentLineageEntryIdFlagName string
	if cmdPrefix == "" {
		segmentLineageEntryIdFlagName = "segmentLineageEntryId"
	} else {
		segmentLineageEntryIdFlagName = fmt.Sprintf("%v.segmentLineageEntryId", cmdPrefix)
	}

	var segmentLineageEntryIdFlagDefault string

	_ = cmd.PersistentFlags().String(segmentLineageEntryIdFlagName, segmentLineageEntryIdFlagDefault, segmentLineageEntryIdDescription)

	return nil
}
func registerOperationSegmentRevertReplaceSegmentsTableNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	tableNameDescription := `Required. Name of the table`

	var tableNameFlagName string
	if cmdPrefix == "" {
		tableNameFlagName = "tableName"
	} else {
		tableNameFlagName = fmt.Sprintf("%v.tableName", cmdPrefix)
	}

	var tableNameFlagDefault string

	_ = cmd.PersistentFlags().String(tableNameFlagName, tableNameFlagDefault, tableNameDescription)

	return nil
}
func registerOperationSegmentRevertReplaceSegmentsTypeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	typeDescription := `Required. OFFLINE|REALTIME`

	var typeFlagName string
	if cmdPrefix == "" {
		typeFlagName = "type"
	} else {
		typeFlagName = fmt.Sprintf("%v.type", cmdPrefix)
	}

	var typeFlagDefault string

	_ = cmd.PersistentFlags().String(typeFlagName, typeFlagDefault, typeDescription)

	return nil
}

func retrieveOperationSegmentRevertReplaceSegmentsForceRevertFlag(m *segment.RevertReplaceSegmentsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("forceRevert") {

		var forceRevertFlagName string
		if cmdPrefix == "" {
			forceRevertFlagName = "forceRevert"
		} else {
			forceRevertFlagName = fmt.Sprintf("%v.forceRevert", cmdPrefix)
		}

		forceRevertFlagValue, err := cmd.Flags().GetBool(forceRevertFlagName)
		if err != nil {
			return err, false
		}
		m.ForceRevert = &forceRevertFlagValue

	}
	return nil, retAdded
}
func retrieveOperationSegmentRevertReplaceSegmentsSegmentLineageEntryIDFlag(m *segment.RevertReplaceSegmentsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("segmentLineageEntryId") {

		var segmentLineageEntryIdFlagName string
		if cmdPrefix == "" {
			segmentLineageEntryIdFlagName = "segmentLineageEntryId"
		} else {
			segmentLineageEntryIdFlagName = fmt.Sprintf("%v.segmentLineageEntryId", cmdPrefix)
		}

		segmentLineageEntryIdFlagValue, err := cmd.Flags().GetString(segmentLineageEntryIdFlagName)
		if err != nil {
			return err, false
		}
		m.SegmentLineageEntryID = segmentLineageEntryIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationSegmentRevertReplaceSegmentsTableNameFlag(m *segment.RevertReplaceSegmentsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("tableName") {

		var tableNameFlagName string
		if cmdPrefix == "" {
			tableNameFlagName = "tableName"
		} else {
			tableNameFlagName = fmt.Sprintf("%v.tableName", cmdPrefix)
		}

		tableNameFlagValue, err := cmd.Flags().GetString(tableNameFlagName)
		if err != nil {
			return err, false
		}
		m.TableName = tableNameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationSegmentRevertReplaceSegmentsTypeFlag(m *segment.RevertReplaceSegmentsParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("type") {

		var typeFlagName string
		if cmdPrefix == "" {
			typeFlagName = "type"
		} else {
			typeFlagName = fmt.Sprintf("%v.type", cmdPrefix)
		}

		typeFlagValue, err := cmd.Flags().GetString(typeFlagName)
		if err != nil {
			return err, false
		}
		m.Type = typeFlagValue

	}
	return nil, retAdded
}

// parseOperationSegmentRevertReplaceSegmentsResult parses request result and return the string content
func parseOperationSegmentRevertReplaceSegmentsResult(respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning revertReplaceSegments default is not supported

		return "", respErr
	}
	return "", nil
}
