// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/spf13/cobra"
	"startree.ai/cli/models"
)

// Schema cli for SegmentPartitionConfig

// register flags to command
func registerModelSegmentPartitionConfigFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerSegmentPartitionConfigColumnPartitionMap(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerSegmentPartitionConfigColumnPartitionMap(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: columnPartitionMap map[string]ColumnPartitionConfig map type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelSegmentPartitionConfigFlags(depth int, m *models.SegmentPartitionConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, columnPartitionMapAdded := retrieveSegmentPartitionConfigColumnPartitionMapFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || columnPartitionMapAdded

	return nil, retAdded
}

func retrieveSegmentPartitionConfigColumnPartitionMapFlags(depth int, m *models.SegmentPartitionConfig, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	columnPartitionMapFlagName := fmt.Sprintf("%v.columnPartitionMap", cmdPrefix)
	if cmd.Flags().Changed(columnPartitionMapFlagName) {
		// warning: columnPartitionMap map type map[string]ColumnPartitionConfig is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
