// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/spf13/cobra"
	"startree.ai/cli/models"
)

// Schema cli for TenantsList

// register flags to command
func registerModelTenantsListFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerTenantsListBROKERTENANTS(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerTenantsListSERVERTENANTS(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerTenantsListBROKERTENANTS(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: BROKER_TENANTS []string array type is not supported by go-swagger cli yet

	return nil
}

func registerTenantsListSERVERTENANTS(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: SERVER_TENANTS []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelTenantsListFlags(depth int, m *models.TenantsList, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, bROKERTENANTSAdded := retrieveTenantsListBROKERTENANTSFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || bROKERTENANTSAdded

	err, sERVERTENANTSAdded := retrieveTenantsListSERVERTENANTSFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || sERVERTENANTSAdded

	return nil, retAdded
}

func retrieveTenantsListBROKERTENANTSFlags(depth int, m *models.TenantsList, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	bROKERTENANTSFlagName := fmt.Sprintf("%v.BROKER_TENANTS", cmdPrefix)
	if cmd.Flags().Changed(bROKERTENANTSFlagName) {
		// warning: BROKER_TENANTS array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveTenantsListSERVERTENANTSFlags(depth int, m *models.TenantsList, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	sERVERTENANTSFlagName := fmt.Sprintf("%v.SERVER_TENANTS", cmdPrefix)
	if cmd.Flags().Changed(sERVERTENANTSFlagName) {
		// warning: SERVER_TENANTS array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
