// Code generated by go-swagger; DO NOT EDIT.

package broker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"startree.ai/cli/models"
)

// GetTablesToBrokersMappingV2Reader is a Reader for the GetTablesToBrokersMappingV2 structure.
type GetTablesToBrokersMappingV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTablesToBrokersMappingV2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTablesToBrokersMappingV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTablesToBrokersMappingV2OK creates a GetTablesToBrokersMappingV2OK with default headers values
func NewGetTablesToBrokersMappingV2OK() *GetTablesToBrokersMappingV2OK {
	return &GetTablesToBrokersMappingV2OK{}
}

/*
GetTablesToBrokersMappingV2OK describes a response with status code 200, with default header values.

successful operation
*/
type GetTablesToBrokersMappingV2OK struct {
	Payload map[string][]models.InstanceInfo
}

// IsSuccess returns true when this get tables to brokers mapping v2 o k response has a 2xx status code
func (o *GetTablesToBrokersMappingV2OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get tables to brokers mapping v2 o k response has a 3xx status code
func (o *GetTablesToBrokersMappingV2OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tables to brokers mapping v2 o k response has a 4xx status code
func (o *GetTablesToBrokersMappingV2OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get tables to brokers mapping v2 o k response has a 5xx status code
func (o *GetTablesToBrokersMappingV2OK) IsServerError() bool {
	return false
}

// IsCode returns true when this get tables to brokers mapping v2 o k response a status code equal to that given
func (o *GetTablesToBrokersMappingV2OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get tables to brokers mapping v2 o k response
func (o *GetTablesToBrokersMappingV2OK) Code() int {
	return 200
}

func (o *GetTablesToBrokersMappingV2OK) Error() string {
	return fmt.Sprintf("[GET /v2/brokers/tables][%d] getTablesToBrokersMappingV2OK  %+v", 200, o.Payload)
}

func (o *GetTablesToBrokersMappingV2OK) String() string {
	return fmt.Sprintf("[GET /v2/brokers/tables][%d] getTablesToBrokersMappingV2OK  %+v", 200, o.Payload)
}

func (o *GetTablesToBrokersMappingV2OK) GetPayload() map[string][]models.InstanceInfo {
	return o.Payload
}

func (o *GetTablesToBrokersMappingV2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
