// Code generated by go-swagger; DO NOT EDIT.

package broker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetTablesToBrokersMappingReader is a Reader for the GetTablesToBrokersMapping structure.
type GetTablesToBrokersMappingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTablesToBrokersMappingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTablesToBrokersMappingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTablesToBrokersMappingOK creates a GetTablesToBrokersMappingOK with default headers values
func NewGetTablesToBrokersMappingOK() *GetTablesToBrokersMappingOK {
	return &GetTablesToBrokersMappingOK{}
}

/*
GetTablesToBrokersMappingOK describes a response with status code 200, with default header values.

successful operation
*/
type GetTablesToBrokersMappingOK struct {
	Payload map[string][]string
}

// IsSuccess returns true when this get tables to brokers mapping o k response has a 2xx status code
func (o *GetTablesToBrokersMappingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get tables to brokers mapping o k response has a 3xx status code
func (o *GetTablesToBrokersMappingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tables to brokers mapping o k response has a 4xx status code
func (o *GetTablesToBrokersMappingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get tables to brokers mapping o k response has a 5xx status code
func (o *GetTablesToBrokersMappingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get tables to brokers mapping o k response a status code equal to that given
func (o *GetTablesToBrokersMappingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get tables to brokers mapping o k response
func (o *GetTablesToBrokersMappingOK) Code() int {
	return 200
}

func (o *GetTablesToBrokersMappingOK) Error() string {
	return fmt.Sprintf("[GET /brokers/tables][%d] getTablesToBrokersMappingOK  %+v", 200, o.Payload)
}

func (o *GetTablesToBrokersMappingOK) String() string {
	return fmt.Sprintf("[GET /brokers/tables][%d] getTablesToBrokersMappingOK  %+v", 200, o.Payload)
}

func (o *GetTablesToBrokersMappingOK) GetPayload() map[string][]string {
	return o.Payload
}

func (o *GetTablesToBrokersMappingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
