// Code generated by go-swagger; DO NOT EDIT.

package upsert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// EstimateHeapUsageReader is a Reader for the EstimateHeapUsage structure.
type EstimateHeapUsageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EstimateHeapUsageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEstimateHeapUsageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEstimateHeapUsageOK creates a EstimateHeapUsageOK with default headers values
func NewEstimateHeapUsageOK() *EstimateHeapUsageOK {
	return &EstimateHeapUsageOK{}
}

/*
EstimateHeapUsageOK describes a response with status code 200, with default header values.

successful operation
*/
type EstimateHeapUsageOK struct {
	Payload string
}

// IsSuccess returns true when this estimate heap usage o k response has a 2xx status code
func (o *EstimateHeapUsageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this estimate heap usage o k response has a 3xx status code
func (o *EstimateHeapUsageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this estimate heap usage o k response has a 4xx status code
func (o *EstimateHeapUsageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this estimate heap usage o k response has a 5xx status code
func (o *EstimateHeapUsageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this estimate heap usage o k response a status code equal to that given
func (o *EstimateHeapUsageOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the estimate heap usage o k response
func (o *EstimateHeapUsageOK) Code() int {
	return 200
}

func (o *EstimateHeapUsageOK) Error() string {
	return fmt.Sprintf("[POST /upsert/estimateHeapUsage][%d] estimateHeapUsageOK  %+v", 200, o.Payload)
}

func (o *EstimateHeapUsageOK) String() string {
	return fmt.Sprintf("[POST /upsert/estimateHeapUsage][%d] estimateHeapUsageOK  %+v", 200, o.Payload)
}

func (o *EstimateHeapUsageOK) GetPayload() string {
	return o.Payload
}

func (o *EstimateHeapUsageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
