// Code generated by go-swagger; DO NOT EDIT.

package segment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"startree.ai/cli/models"
)

// DeleteAllSegmentsReader is a Reader for the DeleteAllSegments structure.
type DeleteAllSegmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAllSegmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAllSegmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAllSegmentsOK creates a DeleteAllSegmentsOK with default headers values
func NewDeleteAllSegmentsOK() *DeleteAllSegmentsOK {
	return &DeleteAllSegmentsOK{}
}

/*
DeleteAllSegmentsOK describes a response with status code 200, with default header values.

successful operation
*/
type DeleteAllSegmentsOK struct {
	Payload *models.SuccessResponse
}

// IsSuccess returns true when this delete all segments o k response has a 2xx status code
func (o *DeleteAllSegmentsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete all segments o k response has a 3xx status code
func (o *DeleteAllSegmentsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete all segments o k response has a 4xx status code
func (o *DeleteAllSegmentsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete all segments o k response has a 5xx status code
func (o *DeleteAllSegmentsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete all segments o k response a status code equal to that given
func (o *DeleteAllSegmentsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete all segments o k response
func (o *DeleteAllSegmentsOK) Code() int {
	return 200
}

func (o *DeleteAllSegmentsOK) Error() string {
	return fmt.Sprintf("[DELETE /segments/{tableName}][%d] deleteAllSegmentsOK  %+v", 200, o.Payload)
}

func (o *DeleteAllSegmentsOK) String() string {
	return fmt.Sprintf("[DELETE /segments/{tableName}][%d] deleteAllSegmentsOK  %+v", 200, o.Payload)
}

func (o *DeleteAllSegmentsOK) GetPayload() *models.SuccessResponse {
	return o.Payload
}

func (o *DeleteAllSegmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
