// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddInstanceReader is a Reader for the AddInstance structure.
type AddInstanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddInstanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddInstanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 409:
		result := NewAddInstanceConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAddInstanceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddInstanceOK creates a AddInstanceOK with default headers values
func NewAddInstanceOK() *AddInstanceOK {
	return &AddInstanceOK{}
}

/*
AddInstanceOK describes a response with status code 200, with default header values.

Success
*/
type AddInstanceOK struct {
}

// IsSuccess returns true when this add instance o k response has a 2xx status code
func (o *AddInstanceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add instance o k response has a 3xx status code
func (o *AddInstanceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add instance o k response has a 4xx status code
func (o *AddInstanceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add instance o k response has a 5xx status code
func (o *AddInstanceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add instance o k response a status code equal to that given
func (o *AddInstanceOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the add instance o k response
func (o *AddInstanceOK) Code() int {
	return 200
}

func (o *AddInstanceOK) Error() string {
	return fmt.Sprintf("[POST /instances][%d] addInstanceOK ", 200)
}

func (o *AddInstanceOK) String() string {
	return fmt.Sprintf("[POST /instances][%d] addInstanceOK ", 200)
}

func (o *AddInstanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddInstanceConflict creates a AddInstanceConflict with default headers values
func NewAddInstanceConflict() *AddInstanceConflict {
	return &AddInstanceConflict{}
}

/*
AddInstanceConflict describes a response with status code 409, with default header values.

Instance already exists
*/
type AddInstanceConflict struct {
}

// IsSuccess returns true when this add instance conflict response has a 2xx status code
func (o *AddInstanceConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add instance conflict response has a 3xx status code
func (o *AddInstanceConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add instance conflict response has a 4xx status code
func (o *AddInstanceConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this add instance conflict response has a 5xx status code
func (o *AddInstanceConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this add instance conflict response a status code equal to that given
func (o *AddInstanceConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the add instance conflict response
func (o *AddInstanceConflict) Code() int {
	return 409
}

func (o *AddInstanceConflict) Error() string {
	return fmt.Sprintf("[POST /instances][%d] addInstanceConflict ", 409)
}

func (o *AddInstanceConflict) String() string {
	return fmt.Sprintf("[POST /instances][%d] addInstanceConflict ", 409)
}

func (o *AddInstanceConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddInstanceInternalServerError creates a AddInstanceInternalServerError with default headers values
func NewAddInstanceInternalServerError() *AddInstanceInternalServerError {
	return &AddInstanceInternalServerError{}
}

/*
AddInstanceInternalServerError describes a response with status code 500, with default header values.

Internal error
*/
type AddInstanceInternalServerError struct {
}

// IsSuccess returns true when this add instance internal server error response has a 2xx status code
func (o *AddInstanceInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this add instance internal server error response has a 3xx status code
func (o *AddInstanceInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add instance internal server error response has a 4xx status code
func (o *AddInstanceInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this add instance internal server error response has a 5xx status code
func (o *AddInstanceInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this add instance internal server error response a status code equal to that given
func (o *AddInstanceInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the add instance internal server error response
func (o *AddInstanceInternalServerError) Code() int {
	return 500
}

func (o *AddInstanceInternalServerError) Error() string {
	return fmt.Sprintf("[POST /instances][%d] addInstanceInternalServerError ", 500)
}

func (o *AddInstanceInternalServerError) String() string {
	return fmt.Sprintf("[POST /instances][%d] addInstanceInternalServerError ", 500)
}

func (o *AddInstanceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
