// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateBrokerResourceParams creates a new UpdateBrokerResourceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateBrokerResourceParams() *UpdateBrokerResourceParams {
	return &UpdateBrokerResourceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateBrokerResourceParamsWithTimeout creates a new UpdateBrokerResourceParams object
// with the ability to set a timeout on a request.
func NewUpdateBrokerResourceParamsWithTimeout(timeout time.Duration) *UpdateBrokerResourceParams {
	return &UpdateBrokerResourceParams{
		timeout: timeout,
	}
}

// NewUpdateBrokerResourceParamsWithContext creates a new UpdateBrokerResourceParams object
// with the ability to set a context for a request.
func NewUpdateBrokerResourceParamsWithContext(ctx context.Context) *UpdateBrokerResourceParams {
	return &UpdateBrokerResourceParams{
		Context: ctx,
	}
}

// NewUpdateBrokerResourceParamsWithHTTPClient creates a new UpdateBrokerResourceParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateBrokerResourceParamsWithHTTPClient(client *http.Client) *UpdateBrokerResourceParams {
	return &UpdateBrokerResourceParams{
		HTTPClient: client,
	}
}

/*
UpdateBrokerResourceParams contains all the parameters to send to the API endpoint

	for the update broker resource operation.

	Typically these are written to a http.Request.
*/
type UpdateBrokerResourceParams struct {

	/* InstanceName.

	   Instance name
	*/
	InstanceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update broker resource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateBrokerResourceParams) WithDefaults() *UpdateBrokerResourceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update broker resource params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateBrokerResourceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update broker resource params
func (o *UpdateBrokerResourceParams) WithTimeout(timeout time.Duration) *UpdateBrokerResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update broker resource params
func (o *UpdateBrokerResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update broker resource params
func (o *UpdateBrokerResourceParams) WithContext(ctx context.Context) *UpdateBrokerResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update broker resource params
func (o *UpdateBrokerResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update broker resource params
func (o *UpdateBrokerResourceParams) WithHTTPClient(client *http.Client) *UpdateBrokerResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update broker resource params
func (o *UpdateBrokerResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstanceName adds the instanceName to the update broker resource params
func (o *UpdateBrokerResourceParams) WithInstanceName(instanceName string) *UpdateBrokerResourceParams {
	o.SetInstanceName(instanceName)
	return o
}

// SetInstanceName adds the instanceName to the update broker resource params
func (o *UpdateBrokerResourceParams) SetInstanceName(instanceName string) {
	o.InstanceName = instanceName
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateBrokerResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param instanceName
	if err := r.SetPathParam("instanceName", o.InstanceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
