// Code generated by go-swagger; DO NOT EDIT.

package tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTablesOnTenantParams creates a new GetTablesOnTenantParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTablesOnTenantParams() *GetTablesOnTenantParams {
	return &GetTablesOnTenantParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTablesOnTenantParamsWithTimeout creates a new GetTablesOnTenantParams object
// with the ability to set a timeout on a request.
func NewGetTablesOnTenantParamsWithTimeout(timeout time.Duration) *GetTablesOnTenantParams {
	return &GetTablesOnTenantParams{
		timeout: timeout,
	}
}

// NewGetTablesOnTenantParamsWithContext creates a new GetTablesOnTenantParams object
// with the ability to set a context for a request.
func NewGetTablesOnTenantParamsWithContext(ctx context.Context) *GetTablesOnTenantParams {
	return &GetTablesOnTenantParams{
		Context: ctx,
	}
}

// NewGetTablesOnTenantParamsWithHTTPClient creates a new GetTablesOnTenantParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTablesOnTenantParamsWithHTTPClient(client *http.Client) *GetTablesOnTenantParams {
	return &GetTablesOnTenantParams{
		HTTPClient: client,
	}
}

/*
GetTablesOnTenantParams contains all the parameters to send to the API endpoint

	for the get tables on tenant operation.

	Typically these are written to a http.Request.
*/
type GetTablesOnTenantParams struct {

	/* TenantName.

	   Tenant name
	*/
	TenantName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get tables on tenant params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTablesOnTenantParams) WithDefaults() *GetTablesOnTenantParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get tables on tenant params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTablesOnTenantParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get tables on tenant params
func (o *GetTablesOnTenantParams) WithTimeout(timeout time.Duration) *GetTablesOnTenantParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tables on tenant params
func (o *GetTablesOnTenantParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tables on tenant params
func (o *GetTablesOnTenantParams) WithContext(ctx context.Context) *GetTablesOnTenantParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tables on tenant params
func (o *GetTablesOnTenantParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tables on tenant params
func (o *GetTablesOnTenantParams) WithHTTPClient(client *http.Client) *GetTablesOnTenantParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tables on tenant params
func (o *GetTablesOnTenantParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTenantName adds the tenantName to the get tables on tenant params
func (o *GetTablesOnTenantParams) WithTenantName(tenantName string) *GetTablesOnTenantParams {
	o.SetTenantName(tenantName)
	return o
}

// SetTenantName adds the tenantName to the get tables on tenant params
func (o *GetTablesOnTenantParams) SetTenantName(tenantName string) {
	o.TenantName = tenantName
}

// WriteToRequest writes these params to a swagger request
func (o *GetTablesOnTenantParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tenantName
	if err := r.SetPathParam("tenantName", o.TenantName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
