// Code generated by go-swagger; DO NOT EDIT.

package tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllTenantsParams creates a new GetAllTenantsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllTenantsParams() *GetAllTenantsParams {
	return &GetAllTenantsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllTenantsParamsWithTimeout creates a new GetAllTenantsParams object
// with the ability to set a timeout on a request.
func NewGetAllTenantsParamsWithTimeout(timeout time.Duration) *GetAllTenantsParams {
	return &GetAllTenantsParams{
		timeout: timeout,
	}
}

// NewGetAllTenantsParamsWithContext creates a new GetAllTenantsParams object
// with the ability to set a context for a request.
func NewGetAllTenantsParamsWithContext(ctx context.Context) *GetAllTenantsParams {
	return &GetAllTenantsParams{
		Context: ctx,
	}
}

// NewGetAllTenantsParamsWithHTTPClient creates a new GetAllTenantsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllTenantsParamsWithHTTPClient(client *http.Client) *GetAllTenantsParams {
	return &GetAllTenantsParams{
		HTTPClient: client,
	}
}

/*
GetAllTenantsParams contains all the parameters to send to the API endpoint

	for the get all tenants operation.

	Typically these are written to a http.Request.
*/
type GetAllTenantsParams struct {

	/* Type.

	   Tenant type
	*/
	Type *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all tenants params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllTenantsParams) WithDefaults() *GetAllTenantsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all tenants params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllTenantsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all tenants params
func (o *GetAllTenantsParams) WithTimeout(timeout time.Duration) *GetAllTenantsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all tenants params
func (o *GetAllTenantsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all tenants params
func (o *GetAllTenantsParams) WithContext(ctx context.Context) *GetAllTenantsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all tenants params
func (o *GetAllTenantsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all tenants params
func (o *GetAllTenantsParams) WithHTTPClient(client *http.Client) *GetAllTenantsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all tenants params
func (o *GetAllTenantsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithType adds the typeVar to the get all tenants params
func (o *GetAllTenantsParams) WithType(typeVar *string) *GetAllTenantsParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the get all tenants params
func (o *GetAllTenantsParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllTenantsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
