// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TableView table view
//
// swagger:model TableView
type TableView struct {

	// o f f l i n e
	OFFLINE map[string]map[string]string `json:"OFFLINE,omitempty"`

	// r e a l t i m e
	REALTIME map[string]map[string]string `json:"REALTIME,omitempty"`
}

// Validate validates this table view
func (m *TableView) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this table view based on context it is used
func (m *TableView) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TableView) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TableView) UnmarshalBinary(b []byte) error {
	var res TableView
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
