// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TaskCount task count
//
// swagger:model TaskCount
type TaskCount struct {

	// completed
	Completed int32 `json:"completed,omitempty"`

	// error
	Error int32 `json:"error,omitempty"`

	// running
	Running int32 `json:"running,omitempty"`

	// total
	Total int32 `json:"total,omitempty"`

	// unknown
	Unknown int32 `json:"unknown,omitempty"`

	// waiting
	Waiting int32 `json:"waiting,omitempty"`
}

// Validate validates this task count
func (m *TaskCount) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this task count based on context it is used
func (m *TaskCount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TaskCount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskCount) UnmarshalBinary(b []byte) error {
	var res TaskCount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
