// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TimestampConfig timestamp config
//
// swagger:model TimestampConfig
type TimestampConfig struct {

	// granularities
	// Read Only: true
	Granularities []string `json:"granularities"`
}

// Validate validates this timestamp config
func (m *TimestampConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGranularities(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var timestampConfigGranularitiesItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["MILLISECOND","SECOND","MINUTE","HOUR","DAY","WEEK","MONTH","QUARTER","YEAR"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		timestampConfigGranularitiesItemsEnum = append(timestampConfigGranularitiesItemsEnum, v)
	}
}

func (m *TimestampConfig) validateGranularitiesItemsEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, timestampConfigGranularitiesItemsEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TimestampConfig) validateGranularities(formats strfmt.Registry) error {
	if swag.IsZero(m.Granularities) { // not required
		return nil
	}

	for i := 0; i < len(m.Granularities); i++ {

		// value enum
		if err := m.validateGranularitiesItemsEnum("granularities"+"."+strconv.Itoa(i), "body", m.Granularities[i]); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validate this timestamp config based on the context it is used
func (m *TimestampConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGranularities(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TimestampConfig) contextValidateGranularities(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "granularities", "body", []string(m.Granularities)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TimestampConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TimestampConfig) UnmarshalBinary(b []byte) error {
	var res TimestampConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
